name: tome
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch=*=*cuda*
  - torchvision=*=*cuda*
  - numpy
  - timm
  - jupyter
  - pip:
    - pillow
    - tqdm
    - scipy
    - torchshow
